### ISSUE TITLE
"Unexpected Escape Sequence" when using menu with arrow keys

### ISSUE THREAD

**Issue by platy** [danielgtaylor/restish#11] opened 2020-10-07 12:09 UTC
While using the api configure menus, the arrow keys cause an error. I can select menu options buy starting to type the text for the option.

```
% restish api configure example
? Base URI http://example.org
Setting up a `default` profile
? Select option for profile `default`  [Use arrows to move, type to filter]
> Add header
  Add query param
  Setup auth
  Finished with profile
ERROR: Caught error: Unexpected Escape Sequence: ['\x1b' 'O']
```

I'm using the regular terminal emulator on MacOS with zsh

**Comment by danielgtaylor** [comment] 2020-10-09 02:07
Interesting... I'm also on Mac and using zsh and it works. Is this an external keyboard? Any idea how I could reproduce?

**Comment by platy** [comment] 2020-10-09 07:33
It was an apple external keyboard. I can't think of anything else to help reproduce - I'll let you know if I come up with anything different.

**Comment by danielgtaylor** [comment] 2020-10-09 18:23
Looks like these might be related:

- https://github.com/romkatv/powerlevel10k/issues/90
- https://github.com/cli/cli/issues/2051

Any chance you are using any zsh plugins? I'm using oh-my-zsh and it seems to work.

**Comment by platy** [comment] 2020-10-12 08:40
I don't have any plugins but I was wondering if it was my custom prompt.
I've tried it again now and it works! - I haven't changed anything though so I don't know what the cause is.

**Comment by danielgtaylor** [comment] 2020-10-15 05:22
Closing for now since it appears to be working. Please reopen if needed!

**Closed by danielgtaylor** 2020-10-15 05:22 UTC
Labels: help wanted
