### ISSUE TITLE
Version 0.11.0 stop working

### ISSUE THREAD

**Issue by 0fefe** [danielgtaylor/restish#81] opened 2022-03-21 21:05 UTC
I upgraded to 0.11.0 version and now I get this error every time I want to run restish command

ERROR: Caught error: yaml: unmarshal errors:
  line 1: cannot unmarshal !!seq into map[string]interface {}

**Comment by danielgtaylor** [comment] 2022-04-03 07:06
@0fefe do you have an example command or response that is causing this so I can reproduce on my side? Did you upgrade from 0.10.0 to 0.11.0 or was it a prior version to that? Any other info to help me track this down?

**Comment by danielgtaylor** [comment] 2022-04-03 19:18
I believe I'm able to reproduce the error with this small code example: https://go.dev/play/p/7_IME0SUEoz

The output (aka responses) which include that seem to work fine, however the command input from stdin seems to be able to produce that error because it assumes the input will be an object rather than possibly being an array. That happens at https://github.com/danielgtaylor/shorthand/blob/main/shorthand.go#L87-L97 but looking back at previous releases I see the old code at https://github.com/danielgtaylor/restish/compare/v0.10.0...v0.11.0#diff-a22a35e46a2a54e56098f46d313be424571104be770e9bf4b63a04f931719722L62-L65 had the same issue and should have also returned an error. Do you have an example that worked before but is not working now? I'm at a bit of a loss...

**Comment by danielgtaylor** [comment] 2022-04-05 05:24
I believe I found the bug. Should be fixed in the next release. Thanks for reporting! :+1:

**Closed** 2022-04-05 05:24 UTC
Labels: question, needs-repro
